(define (make-account balance)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin
                (set! balance (- balance amount))
                balance)
            "Insufficient funds"))
    (define (deposit amount)
        (set! balance (+ balance amount))
        balance)
    (define (dispatch m)
        (cond
            ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            ((eq? m 'confirm) balance)
            (else (error "Unknown request: MAKE-ACCONT:" m))))
    dispatch)

(define mine (make-account 100))
(define yours (make-account 114))
