(define (print-point p)
    (newline)
    (display "(")
    (display (x-point p))
    (display ",")
    (display (y-point p))
    (display ")" ))

(define (make-segment start end)(cons start end))
(define (x-point p)(car p))
(define (y-point p)(cdr p))
(define (start-segment s)(car s))
(define (end-segment s)(cdr s))
(define (mid-point-segment s)
    (cons (/ (+ (car (car s))(car (cdr s)))2) (/ (+ (cdr (car s))(cdr (cdr s)))2)))

